### Test
GET https://xkcd.com/info.0.json

### Main
GET {{url}}

### Get latest comic
GET {{url}}/xkcd/latest

### Get random comic
GET {{url}}/xkcd/random

### Get comic by number
GET {{url}}/xkcd/num/100